/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"
#include "Fatfs.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_ICONVIEW_0   (GUI_ID_USER + 0x00)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
FRESULT res;
// USER END



/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
int _GetData(void * p, const U8 ** ppData, unsigned NumBytes, U32 Off);

static int _OwnerDraw(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo) 
{
	FIL BMPFile;
	ICONVIEW_Handle hIconview;
	hIconview=pDrawItemInfo->hWin;
  switch (pDrawItemInfo->Cmd) 
		{	  			
    case WIDGET_DRAW_BACKGROUND:
			switch(pDrawItemInfo->ItemIndex)
			{
				case 0:
		      res=f_open(&BMPFile,"1.bmp",FA_OPEN_EXISTING|FA_OPEN_ALWAYS|FA_READ);
	        if(res!=FR_OK)
	        {
	         Error_Handler();
	        }
			    GUI_BMP_DrawEx(_GetData,&BMPFile,0,0);	
					
					break;

				default:
          break;					
			}
    default:
    return ICONVIEW_OwnerDraw(pDrawItemInfo);
}
return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
 
  // USER END

  switch (pMsg->MsgId) {
	case WM_PAINT:	
		res=f_open(&SDFile,"Wallpaper.bmp",FA_OPEN_EXISTING|FA_OPEN_ALWAYS|FA_READ);
	  if(res!=FR_OK)
	  {
	   Error_Handler();
	  }
	  GUI_BMP_DrawEx(_GetData,&SDFile,0,0);
   	f_close(&SDFile);
		break;		
		
  case WM_INIT_DIALOG:
    break;			
	
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_0: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)

  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateDeskTop
*/
WM_HWIN CreateDeskTop(void);
WM_HWIN CreateDeskTop(void) {
  WM_HWIN hWin;

	
  WM_SetCallback(WM_HBKWIN,_cbDialog);
	hWin=ICONVIEW_CreateEx(20,20,280,200,WM_HBKWIN,WM_CF_SHOW|WM_CF_HASTRANS,ICONVIEW_CF_AUTOSCROLLBAR_V,ID_ICONVIEW_0,48,48);
  
	ICONVIEW_SetIconAlign(hWin, ICONVIEW_IA_TOP);
	ICONVIEW_SetBkColor(hWin,0,GUI_BLUE);
  ICONVIEW_SetTextColor(hWin, ICONVIEW_CI_UNSEL, GUI_BLUE);
  ICONVIEW_SetTextColor(hWin, ICONVIEW_CI_SEL, GUI_GREEN);
  ICONVIEW_SetFrame(hWin, GUI_COORD_X, 0);//设置图标到IconView边框的间距
  ICONVIEW_SetFrame(hWin, GUI_COORD_Y, 0);
  ICONVIEW_SetSpace(hWin, GUI_COORD_X, (280-64*4)/3);//设置图标和图标之间的间距
  ICONVIEW_SetSpace(hWin, GUI_COORD_Y, (140-64*2)/1);
  ICONVIEW_SetFont(hWin, GUI_FONT_10S_1);
//  ICONVIEW_AddBitmapItem();
//	ICONVIEW_AddBMPItemEx(hWin,&SDFile,_GetData,"Item1");
//	ICONVIEW_AddBMPItemEx(hWin,&SDFile,_GetData,"Item2");		
  	
//ICONVIEW_SetOwnerDraw(hWin,_OwnerDraw);
  return hWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
