/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "widget_ID.h"
#include "stm32f1xx_hal.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern uint8_t Gest;
#define ROCK_TOLERENCE      5.0f
#define PAPER_TOLERENCE     30.0f
#define SCISSORS_TOLERENCE  8.0f

extern float Cap_Mean;

//extern float Cap_Rock;
//extern float Cap_Paper;
//extern float Cap_Scissors;

extern float Cap_Rock_Buf;
extern float Cap_Paper_Buf;
extern float Cap_Scissors_Buf;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "Framewin", Recog_ID_FRAMEWIN_0, 0, 28, 160, 100, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", Recog_ID_TEXT_0, 0, 0, 160, 50, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "Button", Recog_ID_BUTTON_0, 50, 50, 50, 20, 0, 0x0, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
WM_HWIN CreateMenu(void);

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "Recognize");
    FRAMEWIN_SetFont(hItem, GUI_FONT_16_ASCII);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_TEXT_0);
    TEXT_SetText(hItem, "Wait....");
    TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
		  TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00008080));
    
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "Quit");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case Recog_ID_BUTTON_0: // Notifications sent by 'Button'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = pMsg->hWin;
        WM_DeleteWindow(hItem);
        CreateMenu();
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
    // USER START (Optionally insert additional message handling)
  case WM_TIMER:
    
		  if( Cap_Mean !=0 )
				{
					  if( Cap_Rock_Buf !=0 )
							{ 
									if( (Cap_Mean-Cap_Rock_Buf)<=ROCK_TOLERENCE && (Cap_Mean-Cap_Rock_Buf)>=-ROCK_TOLERENCE )
									{
										Gest=1;
									}
						 }
							else
							{
							  Gest=0;
							}
							
					  if( Cap_Paper_Buf !=0 )
							{ 							
									if( (Cap_Mean-Cap_Paper_Buf)<=PAPER_TOLERENCE && (Cap_Mean-Cap_Paper_Buf)>=-PAPER_TOLERENCE )
									{
										Gest=2;
									}	
						 }
							else
							{
							  Gest=0;
							}			

						 if( Cap_Scissors_Buf !=0 )
							{ 								
									if( (Cap_Mean-Cap_Scissors_Buf)<= SCISSORS_TOLERENCE && (Cap_Mean-Cap_Scissors_Buf)>=-SCISSORS_TOLERENCE )
									{
										Gest=3;
									}	
						 }
							else
							{
							  Gest=0;
							}	
							
				}
				else
				{
					 Gest=4;			
				}
		  switch(Gest)
				{
					case 0:
						hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_TEXT_0);
					 TEXT_SetTextAlign(hItem, GUI_TA_LEFT);
						TEXT_SetText(hItem, "  Put your hand on the pla\n-te and DO NOT MOVE!");
						break;
					case 1:
						hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_TEXT_0);
					 TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
						TEXT_SetText(hItem, "Recognized!\nNow is Rock");
						break;	
					case 2:
						hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_TEXT_0);
				 	TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
						TEXT_SetText(hItem, "Recognized!\nNow is Paper");						
						break;
					case 3:
						hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_TEXT_0);
					 TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
						TEXT_SetText(hItem, "Recognized!\nNow is Scissors");							
						break;		
					case 4:
						hItem = WM_GetDialogItem(pMsg->hWin, Recog_ID_TEXT_0);
					 TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
						TEXT_SetText(hItem, "FDC2214 Err!");		
      break;
					
     default:
       break;						
				}
				WM_RestartTimer(pMsg->Data.v, 1000);
    WM_InvalidateWindow(hItem);		
    break;

  // USER END
  default:
			 Gest=0;
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateRecognize(void);
WM_HWIN CreateRecognize(void)
{
  WM_HWIN hWin;
	
		WM_SetCallback(WM_HBKWIN, _cbDialog);
		WM_CreateTimer(WM_HBKWIN, 0, 1000, 0);
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
