/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "widget_ID.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern float Cap_Mean;


float Cap_Rock_Buf;
float Cap_Paper_Buf;
float Cap_Scissors_Buf;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", Train_ID_FRAMEWIN_0, 0, 28, 160, 100, 0, 0x64, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", Train_ID_CHECKBOX_0, 0, 0, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", Train_ID_CHECKBOX_1, 0, 20, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", Train_ID_CHECKBOX_2, 0, 40, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", Train_ID_BUTTON_0, 90, 0, 50, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", Train_ID_BUTTON_1, 90, 40, 50, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
WM_HWIN CreateMenu(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "Train");
    FRAMEWIN_SetFont(hItem, GUI_FONT_16_ASCII);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_CHECKBOX_0);
				CHECKBOX_SetTextAlign(hItem,GUI_TA_VCENTER|GUI_TA_HCENTER );
    CHECKBOX_SetFont(hItem, GUI_FONT_16_ASCII);
    CHECKBOX_SetText(hItem, "Rock");

    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_CHECKBOX_1);
				CHECKBOX_SetTextAlign(hItem,GUI_TA_VCENTER|GUI_TA_HCENTER );
    CHECKBOX_SetFont(hItem, GUI_FONT_16_ASCII);
    CHECKBOX_SetText(hItem, "Paper");

    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_CHECKBOX_2);
				CHECKBOX_SetTextAlign(hItem,GUI_TA_VCENTER|GUI_TA_HCENTER );
    CHECKBOX_SetFont(hItem, GUI_FONT_16_ASCII);
    CHECKBOX_SetText(hItem, "Scissors");

    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "Ok");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "Cancel");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case Train_ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
						  hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_CHECKBOX_0);
			    	if( CHECKBOX_GetState(hItem) )
								{
						  Cap_Rock_Buf=Cap_Mean;
								}
								else
								{
								 Cap_Rock_Buf=0;
								}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case Train_ID_CHECKBOX_1: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
							 hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_CHECKBOX_1);
			    	if( CHECKBOX_GetState(hItem) )
								{
						   Cap_Paper_Buf=Cap_Mean;
								}
								else
								{
								 Cap_Paper_Buf=0;
								}					
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case Train_ID_CHECKBOX_2: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
							 hItem = WM_GetDialogItem(pMsg->hWin, Train_ID_CHECKBOX_2);
			    	if( CHECKBOX_GetState(hItem) )
								{
						   Cap_Scissors_Buf=Cap_Mean;
								}
								else
								{
								 Cap_Scissors_Buf=0;
								}						
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case Train_ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
								hItem = pMsg->hWin;
						  WM_DeleteWindow(hItem);
						  CreateMenu();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case Train_ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
						  Cap_Rock_Buf=0;
					   Cap_Paper_Buf=0;
					   Cap_Scissors_Buf=0;
						
        hItem = pMsg->hWin;
						  WM_DeleteWindow(hItem);
						  CreateMenu();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateTrain(void);
WM_HWIN CreateTrain(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
