/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MyFont33.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Lebment\Desktop\Font24.txt             *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont33;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontMyFont33_0047[ 66] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ____XX__,__XX____,
  ____X___,___X____,
  ___XX___,___XX___,
  __XX____,____X___,
  __XX____,____X___,
  __X_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,_XXXXXX_,
  _XX_____,___XX___,
  _XX_____,___XX___,
  __X_____,___XX___,
  __XX____,___XX___,
  __XX____,___XX___,
  ___X____,___XX___,
  ___XX___,___XX___,
  ____XX__,__X_____,
  _____XXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont33_0050[ 66] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  ___XX___,___XX___,
  ___XX___,____XX__,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,____XX__,
  ___XX___,___XX___,
  ___XXXXX,XXX_____,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont33_0053[ 66] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX__X___,
  ___XX___,_XXXX___,
  __XX____,___XX___,
  _XX_____,___XX___,
  _XX_____,____X___,
  _XX_____,____X___,
  _XX_____,________,
  _XXX____,________,
  __XXXX__,________,
  ___XXXXX,________,
  _____XXX,XX______,
  _______X,XXXX____,
  ________,_XXXX___,
  ________,___XX___,
  ________,___XXX__,
  _X______,____XX__,
  _X______,____XX__,
  _XX_____,____XX__,
  __X_____,____XX__,
  __XX____,___XX___,
  __XXX___,__XX____,
  __X__XXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMyFont33_4EA9[132] = { /* code 4EA9 */
  ________,________,________,________,
  ________,________,________,________,
  ________,____XX__,________,________,
  ________,_____XX_,________,________,
  ________,______XX,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,XX______,________,
  ________,________,X_______,___XX___,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ______X_,________,________,X_______,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,________,________,XX______,
  ______XX,________,________,XX______,
  ______XX,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont33_4EEA[132] = { /* code 4EEA */
  ________,________,________,________,
  ________,________,________,________,
  ________,_X______,________,________,
  ________,_XXX____,X_______,________,
  ________,XXX_____,_X______,________,
  ________,XX______,__X_____,________,
  ________,XX______,__XX____,________,
  _______X,X_______,__XXX___,_X______,
  _______X,X_______,___XX___,_XX_____,
  ______XX,_____X__,___X____,XXX_____,
  ______XX,_____X__,________,XX______,
  ______XX,X_____X_,________,X_______,
  _____XXX,X_____X_,_______X,X_______,
  ____XX_X,X_____X_,_______X,X_______,
  ____X__X,X______X,______XX,________,
  ___XX__X,X______X,______XX,________,
  ___X___X,X_______,X____XX_,________,
  __X____X,X_______,XX___XX_,________,
  _X_____X,X_______,_X___X__,________,
  _______X,X_______,_XX_XX__,________,
  _______X,X_______,__X_X___,________,
  _______X,X_______,__XXX___,________,
  _______X,X_______,__XXX___,________,
  _______X,X_______,_XX_XX__,________,
  _______X,X_______,_X___XX_,________,
  _______X,X_______,X_____XX,X_______,
  _______X,X_____XX,_______X,XX______,
  _______X,X____XX_,________,XXXX____,
  _______X,X___X___,________,_XXXXXX_,
  _______X,X_XX____,________,__XX____,
  _______X,_X______,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont33_6D4B[132] = { /* code 6D4B */
  ________,________,________,________,
  ________,________,________,________,
  ____X___,________,________,___X____,
  ____XX__,__X_____,________,___XX___,
  _____XX_,__XXXXXX,XXXX____,___XX___,
  ______XX,__XX____,__XX____,___XX___,
  ______XX,__XX____,__XX____,___XX___,
  ________,__XX____,__XX__XX,___XX___,
  ________,__XX__X_,__XX__XX,X__XX___,
  ________,__XX__XX,X_XX__XX,___XX___,
  __XX____,__XX__XX,__XX__XX,___XX___,
  ___XX___,X_XX__XX,__XX__XX,___XX___,
  ___XXX__,X_XX__XX,__XX__XX,___XX___,
  ____XX__,X_XX__XX,__XX__XX,___XX___,
  ____X__X,__XX__XX,__XX__XX,___XX___,
  _______X,__XX__XX,__XX__XX,___XX___,
  _______X,__XX__X_,__XX__XX,___XX___,
  _______X,__XX__X_,__XX__XX,___XX___,
  ______X_,__XX__X_,__XX__XX,___XX___,
  ______X_,__XX__X_,__XX__XX,___XX___,
  _____XX_,__XX__X_,__XX__XX,___XX___,
  _XXXXXX_,__XX_XX_,__X___XX,___XX___,
  ___XXX__,__X__XX_,______XX,___XX___,
  ____XX__,_____X_X,______XX,___XX___,
  ____XX__,____XX__,X_______,___XX___,
  ____XX__,____X___,_X______,___XX___,
  ____XX__,___XX___,_XXX____,___XX___,
  ____XX__,__XX____,__XX____,___XX___,
  ____XX__,_XX_____,__XX___X,XXXX____,
  ________,X_______,___X____,_XXX____,
  _______X,________,________,__X_____,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMyFont33_CharInfo[6] = {
   {  16,  16,  2, acGUI_FontMyFont33_0047 } /* code 0047 */
  ,{  16,  16,  2, acGUI_FontMyFont33_0050 } /* code 0050 */
  ,{  16,  16,  2, acGUI_FontMyFont33_0053 } /* code 0053 */
  ,{  32,  32,  4, acGUI_FontMyFont33_4EA9 } /* code 4EA9 */
  ,{  32,  32,  4, acGUI_FontMyFont33_4EEA } /* code 4EEA */
  ,{  32,  32,  4, acGUI_FontMyFont33_6D4B } /* code 6D4B */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont33_Prop6 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontMyFont33_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont33_Prop5 = {
   0x4EEA /* first character */
  ,0x4EEA /* last character  */
  ,&GUI_FontMyFont33_CharInfo[  4] /* address of first character */
  ,&GUI_FontMyFont33_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont33_Prop4 = {
   0x4EA9 /* first character */
  ,0x4EA9 /* last character  */
  ,&GUI_FontMyFont33_CharInfo[  3] /* address of first character */
  ,&GUI_FontMyFont33_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont33_Prop3 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_FontMyFont33_CharInfo[  2] /* address of first character */
  ,&GUI_FontMyFont33_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont33_Prop2 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontMyFont33_CharInfo[  1] /* address of first character */
  ,&GUI_FontMyFont33_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont33_Prop1 = {
   0x0047 /* first character */
  ,0x0047 /* last character  */
  ,&GUI_FontMyFont33_CharInfo[  0] /* address of first character */
  ,&GUI_FontMyFont33_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont33 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMyFont33_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

