/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stm32f1xx_hal.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_4    (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern uint8_t RTCAlarm_Flag;
extern uint8_t WKUP_Flag;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 28, 160, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 0, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 0, 20, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 40, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 0, 60, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 0, 80, 150, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern WM_HWIN CreateLEDSpeed(void);
extern WM_HWIN CreateSetTimeAlarm(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	 BUTTON_SKINFLEX_PROPS Props;  //在原基础上修改
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00000000));

		
				BUTTON_GetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED); //原来的皮肤

				Props.Radius = 0;                                   //圆角的半径。
				Props.aColorUpper[0] = GUI_GRAY ;        //顶部渐变的顶部颜色。
				Props.aColorLower[0] = GUI_WHITE ;        //顶部渐变的底部颜色。
				Props.aColorUpper[1] = GUI_WHITE ;        //底部渐变的顶部颜色。
				Props.aColorLower[1] = GUI_GRAY ;        //底部渐变的底部颜色。
			 Props.aColorFrame[0] = GUI_GREEN;                   //周围框架的外部颜色。
			 Props.aColorFrame[1] = GUI_RED | GUI_LIGHTGRAY;  //周围框架的内部颜色。
			 Props.aColorFrame[2] = GUI_RED | GUI_LIGHTGRAY;  //周围框架与内部矩形区域之间的区域颜色。
				BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED); //更换皮肤		
				
				
				
			 Props.aColorFrame[0] = GUI_ORANGE | GUI_GRAY;                   //周围框架的外部颜色。
			 Props.aColorFrame[1] = GUI_ORANGE ;  //周围框架的内部颜色。
			 Props.aColorFrame[2] = GUI_ORANGE ;  //周围框架与内部矩形区域之间的区域颜色。
				BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_FOCUSSED); //更换皮肤		
				
				Props.aColorFrame[0]= GUI_ORANGE;
    Props.aColorFrame[1]= GUI_ORANGE;
    Props.aColorFrame[2]= GUI_ORANGE;
    Props.aColorLower[0]= GUI_ORANGE;
    Props.aColorLower[1]= GUI_ORANGE;
    Props.aColorUpper[0]= GUI_ORANGE;
    Props.aColorUpper[1]= GUI_ORANGE;
    BUTTON_SetSkinFlexProps(&Props,BUTTON_SKINFLEX_PI_PRESSED); 
				
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		  BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED,GUI_DARKGREEN);
    BUTTON_SetText(hItem, "Set Time And Alarm");
		  
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		  BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED,GUI_DARKGREEN);
    BUTTON_SetText(hItem, "Stop Alarm");
		  
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED,GUI_DARKGREEN);
    BUTTON_SetText(hItem, "Stop Mode");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
				BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED,GUI_DARKGREEN);
    BUTTON_SetText(hItem, "Button4");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
				BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED,GUI_DARKGREEN);
    BUTTON_SetText(hItem, "Set LED Circle");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
								hItem = pMsg->hWin;
						  WM_DeleteWindow(hItem);
						  CreateSetTimeAlarm(); 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
 
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
						  RTCAlarm_Flag=0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
						  WKUP_Flag=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
						  hItem = pMsg->hWin;
						  WM_DeleteWindow(hItem);
						  CreateLEDSpeed(); 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateDesktop(void);
WM_HWIN CreateDesktop(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
