/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MyFont13.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      13                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  13                                           *
* Range disabled:       0000 - FFFF                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont13;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_4E1C[ 26] = { /* code 4E1C */
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XXXX____,
  ____X___,________,
  ___X__X_,________,
  __X___X_,________,
  __XXXXXX,XXX_____,
  ______X_,________,
  ___X__X_,_X______,
  __X___X_,__X_____,
  _X____X_,___X____,
  _____XX_,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5173[ 26] = { /* code 5173 */
  ___X____,_X______,
  ____X___,X_______,
  ________,________,
  __XXXXXX,XXX_____,
  ______X_,________,
  ______X_,________,
  _XXXXXXX,XXXX____,
  ______X_,________,
  _____X_X,________,
  ____X___,X_______,
  ___X____,_X______,
  _XX_____,__XX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5317[ 26] = { /* code 5317 */
  ____X__X,________,
  ____X__X,________,
  ____X__X,___X____,
  ____X__X,__X_____,
  _XXXX__X,_X______,
  ____X__X,X_______,
  ____X__X,________,
  ____X__X,________,
  ___XX__X,________,
  _XX_X__X,___X____,
  ____X__X,___X____,
  ____X___,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5357[ 26] = { /* code 5357 */
  ______X_,________,
  _XXXXXXX,XXXX____,
  ______X_,________,
  __XXXXXX,XXX_____,
  __X_X___,X_X_____,
  __X__X_X,__X_____,
  __X_XXXX,X_X_____,
  __X___X_,__X_____,
  __XXXXXX,XXX_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X_____,XXX_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5F00[ 26] = { /* code 5F00 */
  ________,________,
  __XXXXXX,XXX_____,
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X_______,
  _XXXXXXX,XXXX____,
  ____X___,X_______,
  ____X___,X_______,
  ___X____,X_______,
  ___X____,X_______,
  __X_____,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5F55[ 26] = { /* code 5F55 */
  __XXXXXX,XX______,
  ________,_X______,
  ___XXXXX,XX______,
  ________,_X______,
  _XXXXXXX,XXXX____,
  ______X_,________,
  __X___X_,__X_____,
  ___X_XXX,_X______,
  ____X_X_,X_______,
  ___X__X_,_X______,
  _XX___X_,__XX____,
  _____XX_,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5F85[ 26] = { /* code 5F85 */
  ____X___,X_______,
  ___X____,X_______,
  __X___XX,XXX_____,
  _X__X___,X_______,
  ___X_XXX,XXXX____,
  __XX____,_X______,
  _X_X_XXX,XXXX____,
  ___X____,_X______,
  ___X__X_,_X______,
  ___X___X,_X______,
  ___X____,_X______,
  ___X___X,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_6253[ 26] = { /* code 6253 */
  ___X____,________,
  ___X__XX,XXXX____,
  ___X____,_X______,
  _XXXXX__,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___XXX__,_X______,
  _XXX____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  __XX___X,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_673A[ 26] = { /* code 673A */
  ___X____,________,
  ___X__XX,XX______,
  ___X__X_,_X______,
  _XXXX_X_,_X______,
  ___X__X_,_X______,
  __XXX_X_,_X______,
  __XX_XX_,_X______,
  _X_X__X_,_X______,
  ___X__X_,_X______,
  ___X__X_,_X_X____,
  ___X_X__,_X_X____,
  ___XX___,__XX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_6E05[ 26] = { /* code 6E05 */
  _______X,________,
  _X_XXXXX,XXXX____,
  __X____X,________,
  ____XXXX,XXX_____,
  _______X,________,
  _X_XXXXX,XXXX____,
  __X_X___,__X_____,
  ____XXXX,XXX_____,
  ____X___,__X_____,
  __X_XXXX,XXX_____,
  _X__X___,__X_____,
  ____X___,_XX_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_7B97[ 26] = { /* code 7B97 */
  __X_____,X_______,
  __XXXX__,XXXX____,
  _X__X__X,__X_____,
  ___XXXXX,XX______,
  ___X____,_X______,
  ___XXXXX,XX______,
  ___X____,_X______,
  ___XXXXX,XX______,
  ___X____,_X______,
  _XXXXXXX,XXXX____,
  ____X___,X_______,
  ___X____,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_7EAC[ 26] = { /* code 7EAC */
  ___X____,X_______,
  ___X____,X_______,
  __X__XXX,XXXX____,
  _X__X___,X_______,
  _XXX__XX,XXX_____,
  ___X____,X_______,
  __X__XXX,XXXX____,
  _XXX____,X__X____,
  ________,X__X____,
  ___XX___,X_XX____,
  _XX_____,X_______,
  ________,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_7ECF[ 26] = { /* code 7ECF */
  ___X____,________,
  ___X__XX,XXX_____,
  __X_____,_X______,
  _X__X___,X_______,
  _XXX___X,_X______,
  ___X__X_,__X_____,
  __X__X__,___X____,
  _XXXX_XX,XXX_____,
  ________,X_______,
  ___XX___,X_______,
  _XX_____,X_______,
  _____XXX,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_897F[ 26] = { /* code 897F */
  _XXXXXXX,XXXX____,
  _____X_X,________,
  _____X_X,________,
  __XXXXXX,XXX_____,
  __X__X_X,__X_____,
  __X__X_X,__X_____,
  __X__X_X,__X_____,
  __X_X___,XXX_____,
  __XX____,__X_____,
  __X_____,__X_____,
  __XXXXXX,XXX_____,
  __X_____,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_8BA1[ 26] = { /* code 8BA1 */
  __X_____,X_______,
  ___X____,X_______,
  ________,X_______,
  ________,X_______,
  _XXX____,X_______,
  ___X_XXX,XXXX____,
  ___X____,X_______,
  ___X____,X_______,
  ___X_X__,X_______,
  ___XX___,X_______,
  ___X____,X_______,
  ________,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_8BB0[ 26] = { /* code 8BB0 */
  __X_____,________,
  ___X__XX,XXX_____,
  ________,__X_____,
  ________,__X_____,
  _XXX____,__X_____,
  ___X__XX,XXX_____,
  ___X__X_,________,
  ___X__X_,________,
  ___X_XX_,________,
  ___XX_X_,___X____,
  ___X__X_,___X____,
  _______X,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_95ED[ 26] = { /* code 95ED */
  __X_____,________,
  ___X__XX,XXXX____,
  ________,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X_XXXX,XX_X____,
  __X____X,___X____,
  __X___XX,___X____,
  __X__X_X,___X____,
  __X_X__X,___X____,
  __X___XX,___X____,
  __X_____,_XXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_9664[ 26] = { /* code 9664 */
  ________,X_______,
  _XXX___X,_X______,
  _X_X__X_,__X_____,
  _X_X_X__,___X____,
  _XX___XX,XXX_____,
  _XX_____,X_______,
  _X_X_XXX,XXXX____,
  _X_X____,X_______,
  _X_X__X_,X_X_____,
  _XX__X__,X__X____,
  _X__X___,X__X____,
  _X_____X,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_5E73[ 26] = { /* code 5E73 */
  ________,________,
  __XXXXXX,XXX_____,
  ______X_,________,
  __X___X_,__X_____,
  ___X__X_,__X_____,
  ___X__X_,_X______,
  ______X_,________,
  _XXXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_6D4B[ 26] = { /* code 6D4B */
  ________,___X____,
  _X_XXXXX,___X____,
  __XX___X,_X_X____,
  ___X_X_X,_X_X____,
  ___X_X_X,_X_X____,
  _X_X_X_X,_X_X____,
  __XX_X_X,_X_X____,
  ___X_X_X,_X_X____,
  ___X_X_X,_X_X____,
  __X__X__,___X____,
  _X__X_X_,___X____,
  ___X___X,__XX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_79BB[ 26] = { /* code 79BB */
  ______X_,________,
  _XXXXXXX,XXXX____,
  ____X___,X_______,
  __X__XXX,__X_____,
  __X_X___,X_X_____,
  __XXXXXX,XXX_____,
  ______X_,________,
  _XXXXXXX,XXXX____,
  _X___X__,___X____,
  _X__X__X,___X____,
  _X_XXXXX,X__X____,
  _X______,X_XX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_79EF[ 26] = { /* code 79EF */
  ____X___,________,
  _XXX__XX,XXX_____,
  ___X__X_,__X_____,
  ___X__X_,__X_____,
  _XXXX_X_,__X_____,
  ___X__X_,__X_____,
  __XX__X_,__X_____,
  __XXX_XX,XXX_____,
  _X_X____,________,
  ___X___X,_X______,
  ___X__X_,__X_____,
  ___X_X__,___X____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_7C73[ 26] = { /* code 7C73 */
  ______X_,________,
  __X___X_,__X_____,
  ___X__X_,_X______,
  ____X_X_,X_______,
  _XXXXXXX,XXXX____,
  ______X_,________,
  _____XXX,________,
  ____X_X_,X_______,
  ___X__X_,_X______,
  _XX___X_,__XX____,
  ______X_,________,
  ______X_,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_8DDD[ 26] = { /* code 8DDD */
  ________,________,
  __XXXX_X,XXXX____,
  __X__X_X,________,
  __X__X_X,________,
  __XXXX_X,XXXX____,
  ____X__X,___X____,
  ____X__X,___X____,
  __X_XX_X,___X____,
  __X_X__X,XXXX____,
  __X_X__X,________,
  __X_XX_X,________,
  _XXX___X,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_91CF[ 26] = { /* code 91CF */
  __XXXXXX,XXX_____,
  __X___X_,__X_____,
  __X____X,__X_____,
  _XXXXXXX,XXXX____,
  __X___X_,__X_____,
  __XXXXXX,XXX_____,
  __X___X_,__X_____,
  __XXXXXX,XXX_____,
  ______X_,________,
  __XXXXXX,XXX_____,
  ______X_,________,
  _XXXXXXX,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont13_9762[ 26] = { /* code 9762 */
  ________,________,
  _XXXXXXX,XXXX____,
  ______X_,________,
  _____X__,________,
  __XXXXXX,XXXX____,
  __X__X__,X__X____,
  __X__XXX,X__X____,
  __X__X__,X__X____,
  __X__XXX,X__X____,
  __X__X__,X__X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMyFont13_CharInfo[26] = {
   {  13,  13,  2, acGUI_FontMyFont13_4E1C } /* code 4E1C */
  ,{  13,  13,  2, acGUI_FontMyFont13_5173 } /* code 5173 */
  ,{  13,  13,  2, acGUI_FontMyFont13_5317 } /* code 5317 */
  ,{  13,  13,  2, acGUI_FontMyFont13_5357 } /* code 5357 */
  ,{  13,  13,  2, acGUI_FontMyFont13_5F00 } /* code 5F00 */
  ,{  13,  13,  2, acGUI_FontMyFont13_5F55 } /* code 5F55 */
  ,{  13,  13,  2, acGUI_FontMyFont13_5F85 } /* code 5F85 */
  ,{  13,  13,  2, acGUI_FontMyFont13_6253 } /* code 6253 */
  ,{  13,  13,  2, acGUI_FontMyFont13_673A } /* code 673A */
  ,{  13,  13,  2, acGUI_FontMyFont13_6E05 } /* code 6E05 */
  ,{  13,  13,  2, acGUI_FontMyFont13_7B97 } /* code 7B97 */
  ,{  13,  13,  2, acGUI_FontMyFont13_7EAC } /* code 7EAC */
  ,{  13,  13,  2, acGUI_FontMyFont13_7ECF } /* code 7ECF */
  ,{  13,  13,  2, acGUI_FontMyFont13_897F } /* code 897F */
  ,{  13,  13,  2, acGUI_FontMyFont13_8BA1 } /* code 8BA1 */
  ,{  13,  13,  2, acGUI_FontMyFont13_8BB0 } /* code 8BB0 */
  ,{  13,  13,  2, acGUI_FontMyFont13_95ED } /* code 95ED */
  ,{  13,  13,  2, acGUI_FontMyFont13_9664 } /* code 9664 */
  ,{  13,  13,  2, acGUI_FontMyFont13_5E73 } /* code 5E73 */
  ,{  13,  13,  2, acGUI_FontMyFont13_6D4B } /* code 6D4B */
  ,{  13,  13,  2, acGUI_FontMyFont13_79BB } /* code 79BB */
  ,{  13,  13,  2, acGUI_FontMyFont13_79EF } /* code 79EF */
  ,{  13,  13,  2, acGUI_FontMyFont13_7C73 } /* code 7C73 */
  ,{  13,  13,  2, acGUI_FontMyFont13_8DDD } /* code 8DDD */
  ,{  13,  13,  2, acGUI_FontMyFont13_91CF } /* code 91CF */
  ,{  13,  13,  2, acGUI_FontMyFont13_9762 } /* code 9762 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop26 = {
   0x9762 /* first character */
  ,0x9762 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  25] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop25 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  24] /* address of first character */
  ,&GUI_FontMyFont13_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop24 = {
   0x8DDD /* first character */
  ,0x8DDD /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 23] /* address of first character */
  ,&GUI_FontMyFont13_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop23 = {
   0x7C73 /* first character */
  ,0x7C73 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  22] /* address of first character */
  ,&GUI_FontMyFont13_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop22 = {
   0x79EF /* first character */
  ,0x79EF /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  21] /* address of first character */
  ,&GUI_FontMyFont13_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop21 = {
   0x79BB /* first character */
  ,0x79BB /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  20] /* address of first character */
  ,&GUI_FontMyFont13_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop20 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 19] /* address of first character */
  ,&GUI_FontMyFont13_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop19 = {
   0x5E73 /* first character */
  ,0x5E73 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 18] /* address of first character */
  ,&GUI_FontMyFont13_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop18 = {
   0x9664 /* first character */
  ,0x9664 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 17] /* address of first character */
  ,&GUI_FontMyFont13_Prop19
  
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop17 = {
   0x95ED /* first character */
  ,0x95ED /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 16] /* address of first character */
  ,&GUI_FontMyFont13_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop16 = {
   0x8BB0 /* first character */
  ,0x8BB0 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 15] /* address of first character */
  ,&GUI_FontMyFont13_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop15 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 14] /* address of first character */
  ,&GUI_FontMyFont13_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop14 = {
   0x897F /* first character */
  ,0x897F /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 13] /* address of first character */
  ,&GUI_FontMyFont13_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop13 = {
   0x7ECF /* first character */
  ,0x7ECF /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 12] /* address of first character */
  ,&GUI_FontMyFont13_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop12 = {
   0x7EAC /* first character */
  ,0x7EAC /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 11] /* address of first character */
  ,&GUI_FontMyFont13_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop11 = {
   0x7B97 /* first character */
  ,0x7B97 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[ 10] /* address of first character */
  ,&GUI_FontMyFont13_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop10 = {
   0x6E05 /* first character */
  ,0x6E05 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  9] /* address of first character */
  ,&GUI_FontMyFont13_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop9 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  8] /* address of first character */
  ,&GUI_FontMyFont13_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop8 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  7] /* address of first character */
  ,&GUI_FontMyFont13_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop7 = {
   0x5F85 /* first character */
  ,0x5F85 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  6] /* address of first character */
  ,&GUI_FontMyFont13_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop6 = {
   0x5F55 /* first character */
  ,0x5F55 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  5] /* address of first character */
  ,&GUI_FontMyFont13_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop5 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  4] /* address of first character */
  ,&GUI_FontMyFont13_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop4 = {
   0x5357 /* first character */
  ,0x5357 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  3] /* address of first character */
  ,&GUI_FontMyFont13_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop3 = {
   0x5317 /* first character */
  ,0x5317 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  2] /* address of first character */
  ,&GUI_FontMyFont13_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop2 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  1] /* address of first character */
  ,&GUI_FontMyFont13_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont13_Prop1 = {
   0x4E1C /* first character */
  ,0x4E1C /* last character  */
  ,&GUI_FontMyFont13_CharInfo[  0] /* address of first character */
  ,&GUI_FontMyFont13_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont13 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,13 /* height of font  */
  ,13 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMyFont13_Prop1}
  ,11 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

