/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MyFont24.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Lebment\Desktop\Font24.txt             *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontMyFont24_0020[ 48] = { /* code 0020, SPACE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont24_0042[ 48] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  __XX___X,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX___X,X_______,
  __XXXXXX,________,
  __XX____,XX______,
  __XX____,_X______,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,XX______,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont24_0079[ 48] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX__X,XXX_____,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ____X__X,________,
  ____X__X,________,
  ____XX_X,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____X__,________,
  _____X__,________,
  __X__X__,________,
  __XXX___,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMyFont24_661F[ 72] = { /* code 661F */
  ________,________,________,
  ________,________,________,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,__X_____,
  _____XX_,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,__X_____,
  _____XX_,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,__X_____,
  ________,___X____,________,
  ______X_,___XX___,________,
  _____XX_,___XX___,__X_____,
  _____XXX,XXXXXXXX,XXXX____,
  ____XX__,___XX___,________,
  ____X___,___XX___,________,
  ___X____,___XX___,_X______,
  __X__XXX,XXXXXXXX,XXX_____,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont24_6668[ 72] = { /* code 6668 */
  ________,________,________,
  ________,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XX_,________,__X_____,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____X___,________,_X______,
  ____X_XX,XXXXXXXX,XXX_____,
  ____X___,________,________,
  ____X___,________,____X___,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____X___,X__X____,_X______,
  ____X___,X___X___,X_______,
  ___XX___,X____X_X,________,
  ___X____,X_____X_,________,
  ___X____,X___XX_X,X_______,
  ___X____,XXXX____,XXXXXX__,
  __X____X,XX______,__XXX___,
  _X______,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMyFont24_7941[ 72] = { /* code 7941 */
  ________,________,________,
  ________,________,________,
  _____X__,________,____X___,
  ______XX,______XX,XXXXXX__,
  _______X,______X_,____X___,
  _______X,______X_,___XX___,
  __XXXXXX,XXX___X_,___X____,
  ________,_XX___X_,__X_____,
  ________,XX____X_,__X_____,
  ________,X_____X_,_X______,
  _______X,______X_,_X______,
  ______XX,X_____X_,__X_____,
  _____XXX,_XX___X_,___X____,
  ____X_XX,__XX__X_,____X___,
  __XX__XX,__XX__X_,____X___,
  _X____XX,______X_,____XX__,
  ______XX,______X_,____XX__,
  ______XX,______X_,X___XX__,
  ______XX,______X_,_XXXX___,
  ______XX,______X_,__XX____,
  ______XX,______X_,________,
  ______XX,______X_,________,
  ______XX,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMyFont24_CharInfo[6] = {
   {  12,  12,  2, acGUI_FontMyFont24_0020 } /* code 0020 */
  ,{  12,  12,  2, acGUI_FontMyFont24_0042 } /* code 0042 */
  ,{  12,  12,  2, acGUI_FontMyFont24_0079 } /* code 0079 */
  ,{  24,  24,  3, acGUI_FontMyFont24_661F } /* code 661F */
  ,{  24,  24,  3, acGUI_FontMyFont24_6668 } /* code 6668 */
  ,{  24,  24,  3, acGUI_FontMyFont24_7941 } /* code 7941 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont24_Prop6 = {
   0x7941 /* first character */
  ,0x7941 /* last character  */
  ,&GUI_FontMyFont24_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont24_Prop5 = {
   0x6668 /* first character */
  ,0x6668 /* last character  */
  ,&GUI_FontMyFont24_CharInfo[  4] /* address of first character */
  ,&GUI_FontMyFont24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont24_Prop4 = {
   0x661F /* first character */
  ,0x661F /* last character  */
  ,&GUI_FontMyFont24_CharInfo[  3] /* address of first character */
  ,&GUI_FontMyFont24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont24_Prop3 = {
   0x0079 /* first character */
  ,0x0079 /* last character  */
  ,&GUI_FontMyFont24_CharInfo[  2] /* address of first character */
  ,&GUI_FontMyFont24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont24_Prop2 = {
   0x0042 /* first character */
  ,0x0042 /* last character  */
  ,&GUI_FontMyFont24_CharInfo[  1] /* address of first character */
  ,&GUI_FontMyFont24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMyFont24_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontMyFont24_CharInfo[  0] /* address of first character */
  ,&GUI_FontMyFont24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMyFont24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

