/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
 
#include "stdlib.h"
#include "arm_math.h"
#include "BSP_GPS.h"
#include "BSP_LED.h"
#include "stm32f1xx_hal.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)
#define ID_BUTTON_2    (GUI_ID_USER + 0x03)
#define ID_PROGBAR_0   (GUI_ID_USER + 0x04)
#define ID_SLIDER_0    (GUI_ID_USER + 0x05)
#define ID_RADIO_0     (GUI_ID_USER + 0x06)
#define ID_BUTTON_3    (GUI_ID_USER + 0x07)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

uint8_t Calculate_Type;
uint32_t Distance;

int32_t Sum=0;
int32_t acreage;
int32_t  GPS_X[50];
int32_t  GPS_Y[50];
int32_t  GPS_X_Start;
int32_t  GPS_Y_Start;

extern Guassian_Projection_Typedef  Projection;

extern uint8_t Nb_Of_coordinate;

extern GPS_GPRMC_INFO GPRMC;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMyFont13;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 38, 160, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 30, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 80, 30, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 60, 80, 30, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 80, 0, 80, 15, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 80, 15, 80, 15, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 0, 0, 80, 30, 0, 0x0f02, 0 },
  // USER START (Optionally insert additional widgets)
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 80, 60, 80, 30, 0, 0x0, 0 }, 
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

void GPIO_Analog_ALL_Init(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)

	uint8_t i;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem,&GUI_FontMyFont13);	
    BUTTON_SetText(hItem, "记录");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	  BUTTON_SetFont(hItem,&GUI_FontMyFont13);	
    BUTTON_SetText(hItem, "计算");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
  	BUTTON_SetFont(hItem,&GUI_FontMyFont13);
    BUTTON_SetText(hItem, "清除");
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		RADIO_SetFont(hItem,&GUI_FontMyFont13);
    RADIO_SetText(hItem, "面积测量", 0);
    RADIO_SetText(hItem, "距离测量", 1);
    // USER START (Optionally insert additional code for further widget initialization)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetRange(hItem,1,11);
		SLIDER_SetValue(hItem,11);


    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);	
		BUTTON_SetFont(hItem,&GUI_FontMyFont13);
    BUTTON_SetText(hItem, "待机");
    BUTTON_SetTextColor(hItem,0,GUI_DARKGREEN);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			    if(Nb_Of_coordinate==0)					
					{
       
						GPS_X_Start=(uint32_t)Projection.X;    
						GPS_Y_Start=(uint32_t)Projection.Y;
                   
					  GPS_X[Nb_Of_coordinate]=0;
			      GPS_Y[Nb_Of_coordinate]=0;
          GUI_SetFont(&GUI_Font10_ASCII);
			    GUI_DispDecAt( Nb_Of_coordinate+1,130,25,2);
          GUI_DispDecAt( GPS_X_Start,0,25,8);GUI_DispChar('-');GUI_DispDec(GPS_Y_Start,8);
			    }
					

					else
					{	
            GPS_X[Nb_Of_coordinate]=(uint32_t)Projection.X-GPS_X_Start;
			      GPS_Y[Nb_Of_coordinate]=(uint32_t)Projection.Y-GPS_Y_Start;		
              GUI_SetFont(&GUI_Font10_ASCII);
         GUI_DispDecAt( GPS_X[Nb_Of_coordinate],0,25,8);GUI_DispChar('-');GUI_DispDec(GPS_Y[Nb_Of_coordinate],8);
					}
          	Nb_Of_coordinate++;
            GUI_SetFont(&GUI_Font10_ASCII);
		        GUI_DispDecAt( Nb_Of_coordinate,130,25,2);
            
		    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
		        PROGBAR_SetMinMax(hItem,0,Nb_Of_coordinate);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
       switch(Calculate_Type)
        {
						case 0:
							 for(i=0;i<Nb_Of_coordinate-1;i++)
								{					
									 Sum += GPS_X[i]*GPS_Y[i+1]-GPS_X[i+1]*GPS_Y[i];
									 hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
									 PROGBAR_SetValue(hItem,i+2);
								}
								acreage=abs(Sum)/2;
								GUI_SetFont(&GUI_Font10_ASCII);
								GUI_DispDecAt(acreage,20,10,7);
                GUI_SetFont(&GUI_FontMyFont13);
                GUI_DispString("平米");
						 break;

            case 1:
                Distance=GPS_X[Nb_Of_coordinate]*GPS_X[Nb_Of_coordinate]+GPS_Y[Nb_Of_coordinate]*GPS_X[Nb_Of_coordinate];
                Distance=sqrt(Distance);
                GUI_SetFont(&GUI_Font10_ASCII);
								GUI_DispDecAt(Distance,20,10,7); 
                GUI_SetFont(&GUI_FontMyFont13);
                GUI_DispStringLen("米平",1);
            break;
         }
       
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			  memset(GPS_X,0,Nb_Of_coordinate);
			  memset(GPS_Y,0,Nb_Of_coordinate);
			  Sum=0;
			  Nb_Of_coordinate=0;
        GUI_SetFont(&GUI_Font10_ASCII);
			  GUI_DispDecAt( Nb_Of_coordinate+1,130,25,2);
			  acreage=0;
        GUI_SetFont(&GUI_Font10_ASCII);
			  GUI_DispDecAt( (uint32_t)acreage,20,10,7);
			  hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
		    PROGBAR_SetValue(hItem,0);
			  
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
			  hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
			  TIM3->CCR4= SLIDER_GetValue(hItem);		
		 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
			  hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		     if(RADIO_GetValue(hItem)==1)
					 {
             HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_SET);
             Calculate_Type=1;
           }
				 
				 if(RADIO_GetValue(hItem)==0)
           {
					 HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_RESET);
             Calculate_Type=0;
           }
				 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
			case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
       Blink_LED(100,10);
       Blink_LED(200,10);
       Blink_LED(300,10);

			   if (__HAL_PWR_GET_FLAG(PWR_FLAG_SB) != RESET)
       {
         __HAL_PWR_CLEAR_FLAG(PWR_FLAG_SB);
       }
			GPIO_Analog_ALL_Init(); 
			HAL_PWR_DisableWakeUpPin(PWR_WAKEUP_PIN1);
			 
			__HAL_PWR_CLEAR_FLAG(PWR_FLAG_WU);
			 
			HAL_PWR_EnableWakeUpPin(PWR_WAKEUP_PIN1);
					 
			HAL_PWR_EnterSTANDBYMode(); 
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)



void GPIO_Analog_ALL_Init(void)
{

  GPIO_InitTypeDef GPIO_InitStruct;

  /*Configure GPIO pin : PC13 */
  GPIO_InitStruct.Pin = GPIO_PIN_13;
  GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

  /*Configure GPIO pins :  PA1 PA2 PA3 
                           PA4 PA5 PA6 PA7 
                           PA8 PA9 PA10 PA11 
                           PA12 PA13 PA14 PA15 */
  GPIO_InitStruct.Pin = GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3 
                          |GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7 
                          |GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11 
                          |GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15;
  GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  /*Configure GPIO pins : PB0 PB1 PB2 PB10 
                           PB11 PB12 PB13 PB14 
                           PB15 PB3 PB4 PB5 
                           PB6 PB7 PB8 PB9 */
  GPIO_InitStruct.Pin = GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_10 
                          |GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14 
                          |GPIO_PIN_15|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5 
                          |GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9;
  GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

}
// USER END

/*************************** End of file ****************************/
